export const FETCHING_COIN_DATA = "FETCHING_COIN_DATA";
export const FETCHING_COIN_DATA_SUCCESS = "FETCHING_COIN_DATA_SUCCESS";
export const FETCHING_COIN_DATA_FAIL = "FETCHING_COIN_DATA_FAIL";

export const FETCHING_CRYPTO_DETAILS = "FETCHING_CRYPTO_DETAILS";
export const FETCHING_CRYPTO_DETAILS_SUCCESS = "FETCHING_CRYPTO_DETAILS_SUCCESS";
export const FETCHING_CRYPTO_DETAILS_FAIL = "FETCHING_CRYPTO_DETAILS_FAIL";
